### PR TITLE
Add reordering support

### PR DESCRIPTION
**Pull request by orinocai**
Just including a couple of changes to support reordering of entries from the front-end. Cheers, Rob.

### CODE REVIEW

**Comment by nitriques** [comment]
This is great! Would you mind creating a new version in the extension.meta.xml file please ?

**Comment by orinocai** [comment]
Hmm... actually it's not working in v2.5. I'm back on Monday, will do some more testing then - sorry for the faff.

**Comment by nitriques** [comment]
No stress! We would also need an upgrade path. https://github.com/symphonists/multiuploadfield/blob/master/extension.driver.php#L18-L20 

You can check this example https://github.com/Solutions-Nitriques/oembed_field/blob/master/extension.driver.php#L129-L185 ... It should only be a matter a issuing an alter statement to all data tables like this https://github.com/Solutions-Nitriques/oembed_field/blob/master/fields/field.oembed.php#L976-L1006

**Comment by orinocai** [comment]
Tested and improved: I've implemented it using natural ordering so it doesn't need a schema change. Do you still need a new version in the extension.meta.xml?

**Comment by brendo** [comment]
This is really neat, I'll make some time to pull it down. Yes, we'd still bump the version number to let everyone know this feature is now available :) Thanks!

**Comment by brendo** [comment]
This is great work, I fixed a couple of visual glitches but it all appears to work quite well in Chrome, Firefox and Safari from my testing.

**Comment by orinocai** [comment]
Cool, glad to be able to help :)

**Pull request merged**
