### PR TITLE
Add file's extension to the XML output

### PR DESCRIPTION
**Pull request by jurajkapsz**
Extending XSLT options.

### CODE REVIEW

**Comment by nitriques** [comment]
Would you mind creating a new version in the meta.xml file ? I would release it afterwards.

Thanks!

**Comment by jurajkapsz** [comment]
> Would you mind creating a new version in the meta.xml file ? I would release it afterwards.

Hi @nitriques , something like this?
Sorry, I made a forced push to cleanup my commits, probably not a nice thing.

**Comment by nitriques** [comment]
Oh yes that's perfect! 

@brendo are we ready to merge integration ?

**Comment by jurajkapsz** [comment]
Great, thanks :)

**Comment by nitriques** [comment]
@brendo Ping! :smile:

**Pull request merged**
